#!/usr/bin/python
from tools.timeit import timeit
from tools.fibonacci import genFib

problem = """Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

@timeit
def process():
    value = sum([x for x in genFib(4000000) if (x % 2 == 0)])
    return value
    
etime, solution = process()

print "Problem :\n%s\n\n\nSolution :\n%s" % (problem, solution)
print "\nRunning time : %10.6f seconds" % (etime)

